
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: julelti
  password: Pooh_06202605
  pool: 5

development:
  <<: *default
  database: my_academy_quest_development

test:
  <<: *default
  database: my_academy_quest_test
  

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
